### ISSUE TITLE
False positive rate test suite

### ISSUE THREAD

**Issue by joshlk** [jhgg/pybloof#1]
Hi,

I'v noticed that some of the code was ported from Cassandra bloom filter implementation. [This article] (http://spyced.blogspot.co.uk/2009/01/all-you-ever-wanted-to-know-about.html) is written by the creator of the Cassandra BF and mentions that its a good idea to include tests that test the false positive rate of the filter to make sure there arn't any bugs. It would be useful to include these in pybloof. Would you be interested in adding these in (I can help)? I believe the Cassandra tests are [here](https://github.com/apache/cassandra/blob/4a0d1caa262af3b6f2b6d329e45766b4df845a88/test/unit/org/apache/cassandra/utils/BloomFilterTest.java).

Also, I see that you have ported the calculations modules from Cassandra. In the calculations modules they have two variables to determine optional BF parameters: `buckets per element` and `number of hash functions`. When initialising a BF in pybloof the two parameters are: `size` and `hashes`. Is size the same as `buckets per element`? If not do you know how they relate

Thanks,
Josh

**Comment by jhgg** [comment]
Hey, @joshlk,

Any contribution is welcome. As far as the calculations are concerned, I merely included them so that you can calculate the size and hashes yourself as I didn't really understand the maths behind them too well.

Most of the code here was ported from another library, https://github.com/crankycoder/hydra/ - but tailored and optimized to my use-case. 

I'm not entirely sure if this implementation is 100% correct, so any tests to verify/test for bugs are more than welcome. 

`buckets per element` corresponds to `size` and `number of hash functions` corresponds to `hashes`.

**Comment by joshlk** [comment]
Iv created a pull request which includes: false positive rate (FP) tests and a new bloom_calculator.

When I first ran the tests with parameters determined using BloomCalculations the filters FP performance was very poor. In two websites [1](http://hur.st/bloomfilter?n=20&p=0.1) and [2](http://corte.si/posts/code/bloom-filter-rules-of-thumb) they calculate the parameters using direct equations. This is obviously a lot simpler than the way BloomCalculations works. bloom_calculator uses the equations given in the two websites. The parameters bloom_calculator produces line up with the real FP results. I have therefore removed BloomCalculations. Please have a play with the tests in test_probability.py and see for your self.

**Comment by jhgg** [comment]
Thank you very much! I have these changes and and a new version up on pypi as soon as I get to my computer.

**Comment by jhgg** [comment]
Released:

https://github.com/jhgg/pybloof/releases/tag/v0.7
https://pypi.python.org/pypi/pybloof/0.7
